# Generated by Django 4.0.2 on 2022-03-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='New', max_length=100)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='variety.jpg', null=True, upload_to='variety')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('menu', models.TextField()),
                ('image', models.ImageField(blank=True, default='meal.jpg', null=True, upload_to='meal')),
                ('spicy', models.CharField(choices=[('Not', 'Not'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'), ('ExtraHot', 'ExtraHot')], default='medium', max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('min_order', models.IntegerField(default=1)),
                ('max_order', models.IntegerField(default=20)),
                ('price', models.IntegerField()),
                ('breakfast', models.BooleanField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('display', models.BooleanField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.variety')),
            ],
        ),
    ]
