# Generated by Django 4.0.2 on 2022-03-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_alter_profile_cart_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
