# Generated by Django 4.0.2 on 2022-03-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
