# Generated by Django 4.0.2 on 2022-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0010_alter_meal_discount_alter_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
