# Generated by Django 4.0.2 on 2022-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_alter_meal_discount_alter_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
