# Generated by Django 4.0.2 on 2022-03-04 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paidorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('cart_no', models.CharField(blank=True, max_length=36, null=True)),
                ('payment_code', models.CharField(max_length=36)),
                ('paid_item', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('how_spicey', models.CharField(max_length=100)),
                ('order_no', models.CharField(max_length=50)),
                ('item_paid', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_no', models.CharField(max_length=50)),
                ('paid_cart', models.BooleanField(default=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('pending', 'pending'), ('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='new', max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('admin_remark', models.CharField(default='a', max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('paidorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.paidorder')),
            ],
        ),
        migrations.AddField(
            model_name='paidorder',
            name='shopcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.shopcart'),
        ),
    ]
