# Generated by Django 4.0.2 on 2022-03-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='paidorder',
        ),
        migrations.DeleteModel(
            name='Paidorder',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
