# Generated by Django 4.0.2 on 2022-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_alter_paidorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='admin_remark',
            field=models.CharField(max_length=250),
        ),
    ]
